### ISSUE TITLE
manual

### ISSUE THREAD

**Issue by mohammadreza-ashouri** [Fredda-2/WebTaint#1]
Hello, may you please explain how can I test your tool on a vulnerable java web application?

**Comment by fredrikkadolfsson** [comment]
Hi @megacoder999,

Generate the Agent and RT Jars by running:
`cd WebTaint/root/directory`
`./gradlew clean assemble`

Set up wanted web application and include the _Xbootclasspath_ and _javaagent_ flags.

The code is currently configured to reset the tainted value by clearing the value. This can be seen in TaintTools.java:42-46. That code can also be configured to throw an exception or to log the instance. 

Best way to test the application is then up to you, what I've done is to attack the application with known vulnerabilities and observing if the vulnerability is prevented.
